### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JEFworks** [JEFworks/ubit2#3]
- [x] GSEA tool tip to show genes on hover
- [x] GSEA nicer GO names
- [x] Allow each module to be recomputed individually
- [x] Allow sorting by p-value
- [ ] For large datasets, show top X genes by p-value, or by absolute fold change
- [ ] Barplot of gene variance
- [ ] For large datasets, show top X cells by filtering out low library size, or library complexity
- [x] Draw significance lines for p-value barplot, correspond by coloring on volcano plot
- [x] Color barplots
- [x] Similarly draw threshold line for fold-change barplot, correspond by coloring on volcano plot
- [ ] Switch to cut-tree instead of using k-means
- [ ] Show group label in heatmap with row colors
- [x] Move options to panel drop-down
- [ ] Outlier/failure detection for samples based on lib size and complexity distributions
- [x] Google analytics
- [ ] Link tooltips
- [x] Movable panels?
- [ ] Export data subset
- [x] Export svg as image

**Comment by JEFworks** [comment]
- [ ] allow row annotations
- [ ] allow column annotations
- [ ] heatmap color reverse?
- [ ] drag to make panel heights bigger
- [ ] panel zoom?
- [x] transpose data
- [x] Loading icon
